#Github action that runs on pushing to main in the 2-Automate-Builds folder, builds the dockerfile and tags it with the current date in the format YYYY-MM-DD concatenated with the last 8 characters of a sha1 hash of the commit, afterwards it pushes the image to dockerhub.

on: 
  push:
    branches: [ main ]
    paths:
    - '2-Automate-Builds/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t griftir/section2:$(date +"%Y-%m-%d")-${{ github.sha }} ./2-Automate-Builds
    - name: Push the Docker image to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push griftir/section2:$(date +"%Y-%m-%d")-${{ github.sha }}
