name: build and push


on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build the docker image
      run: docker build -t griftir/section2:${{github.sha}} ./2-Automate-Builds -t griftir/section2:latest
    - name: login to docker
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}
    - name: Push to dockerhub
      run: docker push griftir/section2 --all-tags
